version: "3.8"

volumes:
  postgres:

services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-desafio-03-find-a-friend-api"
    ports:
      - "3333:3333"
      - "5555:5555"
      - "51204:51204"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm run dev"

  db:
    image: bitnami/postgresql
    container_name: "rocketseat-nodejs-desafio-03-find-a-friend-db"
    ports:
      - "54323:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: db_find_a_friend
    volumes:
      - postgres:/data/postgres
